[build]
  publish = "."
  command = "echo 'No build command needed'"

[[redirects]]
  from = "/*"
  to = "/html/app.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/html/app.html"
  status = 200